### ISSUE TITLE
Test data belongs in an external file

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#10]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/include/data.h#L7

I am guessing this is copied straight out of the original? It should really be in a separate 'data' file (or better, several files) so they don't all get compiled in to your executable each time.

**Comment by johnramsden** [comment]
@jnider Yes it's out of the original source. I agree it should be changed in some form.

It's not causing any issues right now, but it definitely will cause issues if multiple files try to include the data.

When you say an extra file, do you mean having an `extern` array and a separate data file so that the data is on the included once? I actually have a branch were already have that working, so if that's what you mean I could easily add it.

Alternatively should I have a "data file" from which I actually read the data into an array?

**Comment by jnider** [comment]
> Alternatively should I have a "data file" from which I actually read the data into an array?
Yes, that's what I meant - then we can easily change the data without having to recompile
