### ISSUE TITLE
Performance: reading small amount of data

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#13]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/src/dpu/dpu_task.c#L45

By my calculation, you are only reading 2*32-bit = 8 bytes at a time from MRAM. That is the absolute minimum transfer, and doesn't have very good performance overall. If you could figure out a way to transfer more (say, 128B or 256B) at a time, the performance should be better, since data transfers are a major source of latency in the DPU.

**Comment by jnider** [comment]
In fact, this read pattern looks linear (unless I missed something?) This could be an excellent candidate for a 'sequential reader' which handles all of the reading and buffering for you - leaving you to read as many (or as few) bytes as you wish with no performance penalty.

**Comment by johnramsden** [comment]
Agreed this was an awful way to do it, I was just trying to get the initial implementation working.

In #5 I'm reading the full size of the buffer all at once:

https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/4362056b54a4af5cec39e035aa473d845e8e86f6/PIM_HDC/src/dpu/dpu_task.c#L32-L34

Since I know I we'll be using the full size of the buffer, does it still make sense to use the sequential reader?

Eventually I plan to either:

1. Stop using static buffers, and allocate a dynamic buffer. For whatever reason when I tried using the buddy allocator I was getting `ENOMEM`, and in order to get #5 functional I used a static buffer to get rid of an extra source of complexity. Using a dynamic buffer would mean I am not allocating more space than I need, which is what I'm doing now (statically).
2. Remove the allocation function completely and just use the sequential reader to access data I need, when I need it. The data is not accessed completely sequentially though (it's accessed in increments of `N`), so I will need to seek the reader if we choose to go this route.

Which option makes more sense to you @jnider ?
