### ISSUE TITLE
Use 'rotate' instead of 'shift'

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-HDC#16]
https://github.com/UBC-ECE-Sasha/PIM-HDC/blob/353dc3d2434e6ff6140f11ead1dd936047fc86a3/PIM_HDC/src/dpu/dpu_task.c#L69

Looks like these 3 lines are trying to do a rotation. There is a machine instruction to do all that in one cycle - ROR: https://sdk.upmem.com/2020.2.1/210_DpuHandbook.html#shift-rotate

No idea how to call it from C - you'll have to do a bit of digging.

**Comment by jnider** [comment]
Conservatively, that little code block is using 6 cycles to do the rotate. If you bring it down to 1, you will save 5*312 cycles per iteration!

**Comment by johnramsden** [comment]
There's actually more than just a rotation here actually.

I do actually get the same output the resulting calculation when I replace the above code with the ROR, however I think that is just because the change is not significant enough to make a difference in the _final_ output result. It _will_ make a difference in the numbers where there is overflow that is non-zero though.

Exact same _final_ result below using `BUILTIN_ROR` or not:

```c
#ifndef BUILTIN_ROR
                overflow = q[0] & MASK;
#endif
                for(int i = 1; i < BIT_DIM; i++) {
#ifdef BUILTIN_ROR
                    __builtin_ror_rri(q[i], q[i], "1");
#else
                    old_overflow = overflow;
                    overflow = q[i] & MASK;
                    q[i] = (q[i] >> 1) | (old_overflow << (32 - 1));
#endif
                    q[i] = q_N[i] ^ q[i];
                }
```

Given that I also I'm not seeing a significant performance increase, I'm going to stick with the original code for now.

Builtin ROR:

```
main: Tasklet 0: completed in 37885488 cycles
main: bit_mod used 260224 cycles (0.006869%)
```

Original:

```
main: Tasklet 0: completed in 37908608 cycles
main: bit_mod used 284544 cycles (0.007506%)
```
